# ORM, Databases
quarkus.datasource.db1.db-kind=postgresql
quarkus.datasource.db1.jdbc.transactions=xa
%dev.quarkus.datasource.db1.jdbc.url=jdbc:postgresql://localhost:5432/db1
quarkus.datasource.db1.username=quarkus
quarkus.datasource.db1.password=quarkus
quarkus.datasource.db1.devservices.enabled=true
%dev.quarkus.datasource.db1.devservices.port=5432
quarkus.datasource.db1.devservices.image-name=quay.io/debezium/postgres:15
quarkus.hibernate-orm.db1.datasource=db1
quarkus.hibernate-orm.db1.database.generation=drop-and-create
quarkus.hibernate-orm.db1.sql-load-script=importDB1.sql
quarkus.hibernate-orm.db1.packages=quarkus.orm.db1
quarkus.datasource.db2.db-kind=mariadb
quarkus.datasource.db2.jdbc.transactions=xa
%dev.quarkus.datasource.db2.jdbc.url=jdbc:mariadb://localhost:49157/db2
quarkus.datasource.db2.username=quarkus
quarkus.datasource.db2.password=quarkus
quarkus.datasource.db2.devservices.enabled=true
%dev.quarkus.datasource.db2.devservices.port=49157
quarkus.datasource.db2.devservices.image-name=quay.io/mariadb-foundation/mariadb-devel:11.0
quarkus.hibernate-orm.db2.datasource=db2
quarkus.hibernate-orm.db2.database.generation=drop-and-create
quarkus.hibernate-orm.db2.sql-load-script=importDB2.sql
quarkus.hibernate-orm.db2.packages=quarkus.orm.db2
# JTA, this is a *toy* dummy test project
quarkus.transaction-manager.enable-recovery=true
quarkus.transaction-manager.object-store.type=file-system
quarkus.transaction-manager.object-store.directory=/tmp/quarkus-jta-blabla
# Config properties injection
injected.value=INJECTED
value=LOOKED UP
# HTTP Server
quarkus.http.port=8080
%test.quarkus.http.port=8081
# REST Client
quarkus.rest-client."quarkus.client.Service".url=http://localhost:${quarkus.http.port}/client/service
# OpenTelemetry Q 3.x
quarkus.otel.traces.exporter=cdi
quarkus.otel.traces.sampler=parentbased_always_on
quarkus.otel.service.name=Demo-Service-A
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
# Uploads
quarkus.http.body.delete-uploaded-files-on-end=true
quarkus.http.limits.max-form-attribute-size=50M
quarkus.http.limits.max-body-size=250M
quarkus.http.body.uploads-directory=/tmp/quarkus-uploads
